version: "3"
services:
  boardsalad:
    container_name: boardsalad
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      NODE_ENV: development
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
  postgres:
    container_name: boardsalad_postgres
    image: postgres:10.4
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
volumes:
  db-data:
